[package]
name = "finite"
version = "0.1.0"
authors = ["Zerthox <zerthox@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8"
